site_name: straindb
site_description: A DRF database to store Brent lab strain data 
repo_url: https://github.com/cmatKhan/brentlab_straindb
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/cmatKhan">cmatKhan</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
